--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12
-- Dumped by pg_dump version 15.12

-- Started on 2025-05-27 10:06:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE aluno_online;
--
-- TOC entry 3354 (class 1262 OID 41033)
-- Name: aluno_online; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE aluno_online WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'pt-BR';


ALTER DATABASE aluno_online OWNER TO postgres;

\connect aluno_online

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 41153)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 41164)
-- Name: aluno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aluno (
    id bigint NOT NULL,
    nome character varying(255),
    cpf character varying(255),
    email character varying(255)
);


ALTER TABLE public.aluno OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 41163)
-- Name: aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.aluno_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.aluno_id_seq OWNER TO postgres;

--
-- TOC entry 3356 (class 0 OID 0)
-- Dependencies: 216
-- Name: aluno_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.aluno_id_seq OWNED BY public.aluno.id;


--
-- TOC entry 218 (class 1259 OID 41173)
-- Name: disciplinas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disciplinas (
    id bigint NOT NULL,
    carga_horaria integer,
    nome character varying(255),
    professor_id bigint
);


ALTER TABLE public.disciplinas OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 41202)
-- Name: disciplinas_id_disciplina_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.disciplinas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disciplinas_id_disciplina_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 41827)
-- Name: matricula_aluno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matricula_aluno (
    id bigint NOT NULL,
    nota1 double precision,
    nota2 double precision,
    status character varying(255),
    aluno_id bigint,
    disciplina_id bigint,
    CONSTRAINT matricula_aluno_status_check CHECK (((status)::text = ANY ((ARRAY['MATRICULADO'::character varying, 'APROVADO'::character varying, 'REPROVADO'::character varying, 'TRANCADO'::character varying])::text[])))
);


ALTER TABLE public.matricula_aluno OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 41826)
-- Name: matricula_aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matricula_aluno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matricula_aluno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 41155)
-- Name: professor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.professor (
    id bigint NOT NULL,
    nome character varying(255),
    cpf character varying(255),
    email character varying(255)
);


ALTER TABLE public.professor OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 41154)
-- Name: professor_id_professor_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.professor_id_professor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.professor_id_professor_seq OWNER TO postgres;

--
-- TOC entry 3357 (class 0 OID 0)
-- Dependencies: 214
-- Name: professor_id_professor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.professor_id_professor_seq OWNED BY public.professor.id;


--
-- TOC entry 3189 (class 2604 OID 41193)
-- Name: aluno id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno ALTER COLUMN id SET DEFAULT nextval('public.aluno_id_seq'::regclass);


--
-- TOC entry 3188 (class 2604 OID 41209)
-- Name: professor id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor ALTER COLUMN id SET DEFAULT nextval('public.professor_id_professor_seq'::regclass);


--
-- TOC entry 3344 (class 0 OID 41164)
-- Dependencies: 217
-- Data for Name: aluno; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.aluno VALUES (3, 'Annette Zieme', '111.111.111-10', 'Isaias.Witting@gmail.com');
INSERT INTO public.aluno VALUES (4, 'Nina Casper', '111.111.111-10', 'Amy.Bradtke29@yahoo.com');
INSERT INTO public.aluno VALUES (5, 'Dr. Danny Reilly DDS', '111.111.111-10', 'Simeon.Kuvalis@yahoo.com');
INSERT INTO public.aluno VALUES (6, 'Lindsay Wehner', '111.111.111-10', 'Aileen22@gmail.com');
INSERT INTO public.aluno VALUES (1, 'Atualizado', '0', 'Atualizado@gmail.com');


--
-- TOC entry 3345 (class 0 OID 41173)
-- Dependencies: 218
-- Data for Name: disciplinas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.disciplinas VALUES (10, 80, 'python', 2);
INSERT INTO public.disciplinas VALUES (11, 80, 'python', 2);
INSERT INTO public.disciplinas VALUES (12, 80, 'Java', 2);
INSERT INTO public.disciplinas VALUES (9, 999, 'Disciplina Atualizada!', 3);


--
-- TOC entry 3348 (class 0 OID 41827)
-- Dependencies: 221
-- Data for Name: matricula_aluno; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.matricula_aluno VALUES (1, NULL, NULL, 'MATRICULADO', 1, 2);
INSERT INTO public.matricula_aluno VALUES (2, 8.5, 7.2, 'MATRICULADO', 1, 2);
INSERT INTO public.matricula_aluno VALUES (3, 8.5, 7.2, 'MATRICULADO', 3, 9);
INSERT INTO public.matricula_aluno VALUES (4, 8.5, 7.2, 'TRANCADO', 3, 9);


--
-- TOC entry 3342 (class 0 OID 41155)
-- Dependencies: 215
-- Data for Name: professor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.professor VALUES (3, 'Maria da Silva', '123.456.789-00', 'maria@gmail.com');
INSERT INTO public.professor VALUES (6, 'Susie Leannon!', '999.999.999-99!', 'atualizado@gmail.com');
INSERT INTO public.professor VALUES (2, 'Rodney Rutherford!', '999.999.999-99!', 'atualizado@gmail.com');


--
-- TOC entry 3358 (class 0 OID 0)
-- Dependencies: 216
-- Name: aluno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.aluno_id_seq', 7, true);


--
-- TOC entry 3359 (class 0 OID 0)
-- Dependencies: 219
-- Name: disciplinas_id_disciplina_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.disciplinas_id_disciplina_seq1', 13, true);


--
-- TOC entry 3360 (class 0 OID 0)
-- Dependencies: 220
-- Name: matricula_aluno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matricula_aluno_id_seq', 4, true);


--
-- TOC entry 3361 (class 0 OID 0)
-- Dependencies: 214
-- Name: professor_id_professor_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.professor_id_professor_seq', 6, true);


--
-- TOC entry 3194 (class 2606 OID 41195)
-- Name: aluno aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_pkey PRIMARY KEY (id);


--
-- TOC entry 3196 (class 2606 OID 41832)
-- Name: matricula_aluno matricula_aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT matricula_aluno_pkey PRIMARY KEY (id);


--
-- TOC entry 3192 (class 2606 OID 41211)
-- Name: professor professor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT professor_pkey PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 41223)
-- Name: disciplinas fkh8enxwkgipjphmwcl6212acau; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplinas
    ADD CONSTRAINT fkh8enxwkgipjphmwcl6212acau FOREIGN KEY (professor_id) REFERENCES public.professor(id);


--
-- TOC entry 3198 (class 2606 OID 41833)
-- Name: matricula_aluno fkn1iea49e3kxfecd5e27i7lvak; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT fkn1iea49e3kxfecd5e27i7lvak FOREIGN KEY (aluno_id) REFERENCES public.aluno(id);


--
-- TOC entry 3355 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


-- Completed on 2025-05-27 10:06:30

--
-- PostgreSQL database dump complete
--

